### ISSUE TITLE
Perform face to face UX testing/feedback on existing monarch app

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-ui-new#37]
In addition to gathering feature requests and UX feedback per #7 , face-to-face testing demos could be performed for valuable insight. However this may not be possible for a while due to covid.

Here's what we had proposed previously for what the goal of these face to face sessions should and how they should be conducted.

"User outreach and usability evaluation efforts will drive the development of new features in the Monarch website. Inspection techniques such as heuristic evaluation (assessing adherence to best practices) and cognitive walkthroughs will be used to assess new designs. Think-aloud usability studies at key scientific meetings will provide insight into difficulties that users might encounter. Testing sessions may range from capturing first impressions through Five Seconds tests to completing more complex use-case challenges during Tree Testing and Card Sorting sessions that will assess suitability of our tools for specific problems; these sessions will also include Moderated and Unmoderated tests, which quantitatively and qualitatively characterize the user’s interaction with the site. Our goal is to rapidly feed back any problems identified with user experience into site modifications. "

**Comment by vincerubinetti** [comment]
This has been performed -- at least, as much as it likely can be for the foreseeable future due to covid -- as part of the user interviews. See #7 for links to interview notes/vids/etc.
