### ISSUE TITLE
Gather old user research

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-ui-new#5]
- [x] locate any old conference research where user testing was conducted
- [x] @jmcmurry document any old user research that you remember

**Comment by putmantime** [comment]
- [ ] locate any old conference research where user testing was conducted
- [ ] @jmcmurry document any old user research that you remember

**Comment by jmcmurry** [comment]
overview is [here](https://docs.google.com/document/d/1L71pMHCQdJV2LqKTd2JhxSqy8E4Q62tq-RJCt7Dvhok/edit)
