### ISSUE TITLE
List addressable common themes from all the interviews

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-ui-new#54]

**Comment by vincerubinetti** [comment]
Completed and captured in [product spec sheet](https://docs.google.com/document/d/1eawNRvU9jr7l-pCWFxhw7D6wvvBq1PTRHyPqGCAZlY0/edit).
[User interviews](https://docs.google.com/document/d/1KTctXmAvSK-7fkJmXcvbULVCyG5Bn8YCYq2jGe31Hfw/edit)
