### ISSUE TITLE
Gather user research through Interviews

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-ui-new#7]
Conduct 1 on 1 interviews to gather feature enhancement requests, overall UX input, and design notes  from each Monarch Lead separately

- [x] Melissa Haendel
- [x] Peter Robinson (scheduled)
- [x] Chris Mungall 
- [ ] David Osumi-Sutherland
- [ ] Damian Smedley (scheduled)

Additional: 
- [x] Val Wood (scheduled)
- [ ] Nicole Vasilevsky (scheduled)
- [ ] Leigh Carmody
- [ ] Sue Bello
- [ ] Lauren Chan
- [ ] Alex Wagner
- [ ] Allison Heath
- [x] Anne Thessen
- [x] Sabrina Toro
- [x] Alexa Burger

**Comment by putmantime** [comment]
@vincerubinetti and I came up with a list of questions that we can ask during interviews.
Please feel free to add to this.

Interview Template (Please include Vince if possible in the Interview)

- What have you traditionally disliked about the Monarch UI?
    - What are specific pain points with using the Monarch UI?

- What have you traditionally liked about the Monarch UI?

- Who is Monarch’s target audience? 
    - Identify the different users/roles

- What are the primary use cases you want Monarch to be able to support? 
    - Identify specific user stories for each role
- How does Monarch compare to other web applications you have used?  
    - Biomedical or any UX you have experience with.

- How do you typically use the Monarch UI when you use it?

- Could you recommend a true Monarch end user for us to interview?

- Without adding any new features, what do you think could be done to improve the existing monarch experience?

- Do you have a wishlist of features you would like to see implemented?

**Comment by monicacecilia** [comment]
We are gathering feedback at https://bit.ly/mi-ui-2021 - the document also contains links to recordings.

**Comment by vincerubinetti** [comment]
Market research notes here: https://docs.google.com/document/d/15zSxos9M7d0ri1gn7Rp6TSFVRGJFjMyxwbhxm5R6Ibc/edit
