### ISSUE TITLE
Gather market research

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-ui-new#8]
Gather more info [here](https://docs.google.com/document/d/15zSxos9M7d0ri1gn7Rp6TSFVRGJFjMyxwbhxm5R6Ibc)

**Comment by jmcmurry** [comment]
here's what we proposed:
"User outreach and usability evaluation efforts will drive the development of new features in the Monarch website. Inspection techniques such as heuristic evaluation (assessing adherence to best practices) and cognitive walkthroughs will be used to assess new designs. Think-aloud usability studies at key scientific meetings will provide insight into difficulties that users might encounter. Testing sessions may range from capturing first impressions through Five Seconds tests to completing more complex use-case challenges during Tree Testing and Card Sorting sessions that will assess suitability of our tools for specific problems; these sessions will also include Moderated and Unmoderated tests, which quantitatively and qualitatively characterize the user’s interaction with the site. Our goal is to rapidly feed back any problems identified with user experience into site modifications. "
