### ISSUE TITLE
gather SEO Data from google search console

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/monarch-ui-new#9]
Examine the GSC data in depth and see if there are any insights to glean from it that will improve the new app vs the old. Examples might be lack of sitemap, lack of sufficient metadata, etc.

**Comment by vincerubinetti** [comment]
@kevinschaper Don't worry too much about this. There's probably not too much data or insight to gain here. Most of the errors it reports I believe will be the same types of things that a [usual SEO checker](https://sitechecker.pro/) will report, and these are things I already know to do in the new app.

If you want, you could just list any errors it reports, and/or screenshot any other special views in the GSC UI that I don't know about, and just call this closed.

**Comment by putmantime** [comment]
Closed due to no longer needed
